### ISSUE TITLE
Zeitwerk conflicts with Rails 6

### ISSUE THREAD

**Issue by davidw** [bigcommerce/gruf#105]
## Please describe the issue

When I place the `_pb.rb` files in `app/proto`, the system fails to load them because they don't comply with the filename must match class name policy.

## How to Reproduce

Generate some Ruby files from a .proto file. Place them somewhere rails can find them.

## What _should_ happen?

Gruf should start up and run.

## Anything else we should know?

I got it to at least start by doing this in `application.rb`:

`Rails.autoloaders.main.ignore(Rails.root.join('app/proto/'))`

**Comment by splittingred** [comment]
Hello! A few things:

1) This is an issue with the [grpc core library](https://github.com/grpc/grpc), unfortunately, not gruf
2) A simple workaround is to not put your proto files in an autoloaded directory by Rails, and require them manually. Furthermore - I'd strongly recommend instead putting your generated proto files into a gem (built via CI), and then including that gem in any services that need it. This allows you to use those files centrally across services without having to worry about duplicated RPC contracts, and isolates the build process (and file loading process!) from your service.

Going to close this, as this isn't an issue with gruf specifically. Thanks!

**Comment by davidw** [comment]
Perhaps on the wiki you could add some more explicit instructions on the quickest way to get gruf up and running to check it out, saving refactoring proto files/code into separate repositories and such for later.

**Comment by Mayurifag** [comment]
@davidw Did you have success with your gruf client on zeitwerk rails server after generating proto files? May I ask you to share your solution if so? 😅  Didn't you create the issue on grpc library repository? Can't find it.

@splittingred Thanks for your work here!! 😄  Could you please share an example what's right way to require these generated files in rails environment? Yea, sorry, not everyone use hanami or other simple frameworks with manual requires. Isn't it something like that, which won't work anyways:

```ruby
# application.rb
...
???
all_files_ending_with_services_pb_rb.each do |file|
  require "#{file}"
end
```

Sorry for asking, but this question is not so obvious for me. And I wish, we may find solution here — and it would be not to create yet another gem for protos just because it won't be rails-zeitwerk based. If its too hard to overcome zeitwerk's 'requires' — shall users think about dirty-hack solutions like bash script that will move the generated files on its places & cleaning unneeded requires?
