### ISSUE TITLE
How to make Gruf server to auto reload code change?

### ISSUE THREAD

**Issue by nimid** [bigcommerce/gruf#115]
## What? Why?

How to make Gruf server to auto reload code change?

Every time I made a code change, I need to stop Gruf server and then start it again to make the changed source code to be applied.

**Comment by pedelman** [comment]
This is a really cool idea, I wonder if there is an opportunity for us to create a [Guard](https://github.com/guard/guard) plugin for Gruf. This would make a pretty cool open source project, I can think of lots of folks who could benefit from it.

I did some poking around and found this project that seems like it could be used as a rough starting point, I imagine we would want to do something similar (just using Gruf rather than Rack). https://github.com/dblock/guard-rack

I did notice that this issue seems somewhat related to #86, there are some subtle differences, but if the goal is to avoid having to manually start and stop the server when we detect file changes, Guard seems like it might be the most straightforward way to achieve this.

Is this something you would be interested in working on? I think it would make sure for a pretty cool project!

**Comment by splittingred** [comment]
This has now been accomplished for gruf controllers in https://github.com/bigcommerce/gruf/releases/tag/v2.15.0 - note you'll need to remove `app/rpc` from any zeitwerk management you may be doing in your apps if you were doing it as a stop-gap. Feel free to re-open if you find any issues or extra functionality you'd like!
