### ISSUE TITLE
[Question] Raising custom errors from client interceptors

### ISSUE THREAD

**Issue by fteem** [bigcommerce/gruf#128]
My question is: what is the most idiomatic way to throw a custom error in a client interceptor that is not defined in the [`Gruf::Client::Errors`](https://github.com/bigcommerce/gruf/blob/bb3800e2487398cdf7acbdaef30e3927869f611f/lib/gruf/client/error.rb) module?

My goal is to write a client interceptor, that in certain conditions will throw the custom error and expose that error type instance to the caller of the client (instead of the default `Gruf::Client::Errors::Internal`).

An example interceptor:

```ruby
class MyCustomError < StandardError; end

class MyInterceptor < Gruf::Interceptors::ClientInterceptor
  def call(request_context:)
    raise MyCustomError.new('An error') if some_condition?
    
    yield
  end
end
```

If I would to use `MyInterceptor` from the example above in a `Gruf::Client` instance, invoking `call` will result in a `Gruf::Client::Errors::Internal` error being thrown (instead of `MyCustomError`).

This behavior is expected, as gruf's `ErrorFactory` [falls back](https://github.com/bigcommerce/gruf/blob/bb3800e2487398cdf7acbdaef30e3927869f611f/lib/gruf/client/error_factory.rb) to `Gruf::Client::Errors::Internal` (the default error type) if the returned error type from the interceptor is not a subclass of `Gruf::Client::Errors::Base`. 

I was able to work around this by defining `MyCustomError` as subclass of `Gruf::Client::Errors::Base` like:

```ruby
MyCustomError = Class.new(Gruf::Client::Errors::Base)
```

This ☝️ seems hacky to me, and as this is the first client interceptor that I am writing, and the wiki does not say much on the topic (unless I have misunderstood/missed it), I decided to open this issue and ask if there's a better way to achieve the same result.

Thank you for all your work on `gruf`, and thank you in advance for taking the time to read my question and reply. 🙏

**Comment by splittingred** [comment]
Hi @fteem - Gruf doesn't support a custom ErrorFactory for client errors at this time. I'm not sure we want to either - given that the error factory is what explicitly handles mapping gRPC status codes to gruf client errors. It's worth considering maybe making it injectable, at least, to allow you to override it.

You can consider the `Gruf::Client::Errors` contractual, and they should not change, so they would be safe to subclass if you want to handle it such. That would be my recommendation - consider those classes as an inheritance model rather than "hacky" (similarly to how StandardError works today in Ruby).

**Comment by splittingred** [comment]
Closing as no further comments in a few months. Thanks!
