### ISSUE TITLE
Starting Gruf in a Docker Container

### ISSUE THREAD

**Issue by wrudnick20spokes** [bigcommerce/gruf#129]
## Please describe the issue

It doesn't appear that running `bundle exec gruf` in a `Dockerfile` is properly executing/initializing a gRPC server.

See this repo: https://github.com/drn/gruf-docker

## How to Reproduce

1. Write a Dockerfile for your gruf project, with `CMD bundle exec gruf` to start the server
2. Build and run the Docker container
3. See that in the logs it never appears to start the gRPC server
4. Using `grpcurl` you can see that the gRPC server is not running at the host/port defined in gRUF
 
## What _should_ happen?

The gRPC server starts as expected

## Anything else we should know?

* Ruby version 2.7

**Comment by splittingred** [comment]
Hi @wrudnick20spokes - it seems you have:

```
EXPOSE 50051
```

here: https://github.com/drn/gruf-docker/blob/master/Dockerfile#L44

But gruf binds to [9001 by default](https://github.com/bigcommerce/gruf/blob/main/lib/gruf/configuration.rb#L25)

**Comment by splittingred** [comment]
Got it - so, unless you're providing a dummy loopback interjection such as Envoy/cni, or other networking tooling, you need to bind to `0.0.0.0` rather than to `localhost`/`127.0.0.1` (the loopback) - this allows grpc to properly respond to ingress requests.

This is essentially because Docker containers have their own network namespace, and so binding to the loopback within it only exposes the software within that namespace. Requests to your container are going to a bridge, rather than the internal loopback of the container networking namespace.

To solve this, you can use something like [Envoy](https://www.envoyproxy.io/) and/or [cni](https://github.com/containernetworking/cni), but for most that is overkill and you instead just need to tell your application (here, gruf) to listen on _all interfaces_ (`0.0.0.0`).

**Comment by wrudnick20spokes** [comment]
Thanks for the quick responses @splittingred!

I tried binding to `0.0.0.0`  and I'm still seeing the same issue - like it's not even trying to spin up the gruf server.

See my docker compose output:

```
 ⠿ Container v2-cluster_users_1  Created                                                           0.0s
Attaching to users_1
```

And that's it, no other logs ever appear.

**Comment by splittingred** [comment]
Hi @wrudnick20spokes - I think there's some problems with your Dockerfile and docker-compose. Either way - I've added a Dockerfile + docker-compose.yml to https://github.com/bigcommerce/gruf-demo, so you can see how it works:

```
$ docker-compose up
Recreating gruf_demo ... done
Attaching to gruf_demo
gruf_demo    | - Loading gRPC service file: /opt/app/app/rpc/products_controller.rb
```

Then in CLI, I did (replace 1.2.3.4 with your docker IP, and the port with the port that was exposed):

```
GRPC_SERVER_URL=1.2.3.4:32772 bundle exec rake test:get_product
calling 1.2.3.4:32772:/rpc.Products/GetProduct
<Rpc::GetProductResp: product: <Rpc::Product: id: 1, name: "Durable Bronze Chair", price: 9.100000381469727>>
```

**Comment by wrudnick20spokes** [comment]
Thank you so much for your help @splittingred - I've gotten it working. Issue was definitely my `Dockerfile`
